export const CHECKED = "2026-09-24";
export const MAJORS = [
  "Computer Science",
  "Engineering",
  "Business Administration",
  "Biology",
  "Psychology",
  "Fine Arts",
  "Chemistry",
  "Communications",
  "Economics",
  "Education",
  "English",
  "Environmental Science",
  "History",
  "Journalism",
  "Mathematics",
  "Music",
  "Nursing",
  "Physics",
  "Political Science",
  "Sociology",
];
export const PROJECTS = {
  "Computer Science":
    "Build a small tool that solves a problem for a local organization. Test it with three people and publish the code and a short case study.",
  Engineering:
    "Design and test a low-cost prototype. Record constraints, measurements, failed attempts, and the next design iteration.",
  "Business Administration":
    "Interview five potential users about a real problem. Test a small service and document costs, feedback, and what you changed.",
  Biology:
    "Investigate a local biodiversity question with public observations. Document your method, limitations, and an illustrated report.",
  Psychology:
    "Compare research on a learning or behavior question. Write an evidence review using published studies rather than collecting sensitive personal data.",
  "Fine Arts":
    "Create a cohesive series of six works around one question. Document sketches, critique, revisions, and an accessible portfolio.",
  Chemistry:
    "Use open chemical data to investigate a materials question. Create a reproducible analysis and explain the limits of your conclusions.",
  Communications:
    "Help a community organization explain one issue. Create three communication formats and evaluate clarity with reader feedback.",
  Economics:
    "Analyze a local economic question with public data. Publish your assumptions, charts, methods, and competing explanations.",
  Education:
    "Design a short learning resource with an educator. Revise it after feedback and document how it supports a specific learning objective.",
  English:
    "Develop a close-reading essay series or an edited literary collection. Keep drafts and explain your editorial decisions.",
  "Environmental Science":
    "Map a local environmental question using public data. Create a clear report with limitations and a practical community action.",
  History:
    "Build a small digital exhibit from public-domain primary sources. Add citations, context, and a note on whose perspectives are missing.",
  Journalism:
    "Report a local public-interest story. Verify claims, seek permission for interviews, and publish a sourced article with corrections contact.",
  Mathematics:
    "Explore one mathematical problem in depth. Write rigorous explanations, test examples, and publish a readable notebook.",
  Music:
    "Create and record a short original composition or arrangement. Document practice, feedback, and revisions in a listening portfolio.",
  Nursing:
    "Create a health-literacy resource from authoritative public sources with review from a qualified professional. Do not offer individual medical advice.",
  Physics:
    "Investigate a physical system with a simulation or safe measurements. Compare predictions with results and explain uncertainty.",
  "Political Science":
    "Compare public policy approaches using primary documents and open data. Publish a balanced brief with explicit assumptions.",
  Sociology:
    "Explore a community question using published research and public aggregate data. Write a report that distinguishes evidence from interpretation.",
};
const item = (
  id,
  title,
  organization,
  category,
  majors,
  summary,
  url,
  eligibility,
  evidence,
  extra = {},
) => ({
  id,
  title,
  organization,
  category,
  majors,
  summary,
  url,
  eligibility,
  evidence,
  checked: CHECKED,
  format: "Remote",
  cost: "Free",
  timing: "Start anytime",
  status: "ongoing",
  minAge: 0,
  review: false,
  ...extra,
});
export const opportunities = [
  item(
    "by-the-people",
    "By the People transcription",
    "Library of Congress",
    "Volunteering",
    [
      "History",
      "English",
      "Political Science",
      "Music",
      "Journalism",
      "Sociology",
    ],
    "Make historical documents easier to find and read by transcribing and reviewing digitized collections.",
    "https://crowd.loc.gov/",
    "Everyone is welcome. Read the transcription instructions; reviewing completed pages requires an account.",
    "A contribution record and reflection on a primary-source collection.",
    { source: "https://crowd.loc.gov/about/" },
  ),
  item(
    "librivox",
    "Public-domain audiobook recording",
    "LibriVox",
    "Volunteering",
    ["English", "Music", "Communications", "Fine Arts", "History"],
    "Help turn public-domain books into freely available audiobooks.",
    "https://librivox.org/pages/about-librivox/",
    "No prior recording experience required. You need a computer and microphone; follow the recording guide and rights rules for your location.",
    "A recorded chapter and reflection on narration, editing, and feedback.",
  ),
  item(
    "idealist",
    "Social-impact internships",
    "Idealist",
    "Internship directory",
    [
      "Political Science",
      "Sociology",
      "Communications",
      "Journalism",
      "Economics",
      "Business Administration",
      "Environmental Science",
      "Education",
      "Psychology",
    ],
    "Browse remote internships with nonprofit and social-impact organizations.",
    "https://www.idealist.org/en/remote-internship-opportunities",
    "Directory, not a guaranteed placement. Each employer sets enrollment, age, location, work authorization, hours, and pay. Confirm that high-school graduates can apply.",
    "A verified internship shortlist and tailored application materials.",
    { review: true, cost: "Varies", timing: "Employer deadlines vary" },
  ),
  item(
    "mlh-fellowship",
    "Open Source Fellowship",
    "Major League Hacking",
    "Fellowship",
    ["Computer Science", "Engineering"],
    "A 12-week internship alternative contributing to open-source projects with support from mentors.",
    "https://fellowship.mlh.com/programs/open-source",
    "Check the age requirement (18+), coding proficiency, country restrictions, and time-zone availability. Requires at least 20 hours each week for 12 weeks; admission is selective.",
    "Reviewed code contributions and a technical project narrative.",
    {
      minAge: 18,
      minHours: 20,
      review: true,
      cost: "Check program",
      timing: "Cohort applications · check current schedule",
    },
  ),
  item(
    "nccc",
    "AmeriCorps NCCC service",
    "AmeriCorps",
    "National service",
    [
      "Environmental Science",
      "Political Science",
      "Sociology",
      "Education",
      "Engineering",
      "Nursing",
    ],
    "Explore a residential, team-based service year supporting communities across the United States.",
    "https://www.americorps.gov/serve/americorps/americorps-nccc",
    "Volunteer roles are generally ages 18–24; Traditional Corps allows applying at 17 if 18 by arrival. U.S. citizenship or permanent residence and track-specific rules apply. Full-time service with extensive travel for 10–11 months; not a part-time commitment.",
    "A sustained service record with documented responsibilities and team contributions.",
    {
      minAge: 17,
      maxAge: 24,
      minHours: 40,
      review: true,
      format: "Local",
      cost: "Check program",
      timing: "Full-time residential service · check current openings",
    },
  ),
  item(
    "space-apps",
    "NASA Space Apps Challenge",
    "NASA",
    "Hackathon",
    [
      "Computer Science",
      "Engineering",
      "Physics",
      "Environmental Science",
      "Fine Arts",
      "Communications",
    ],
    "Work with a team on a challenge using NASA and partner open data.",
    "https://www.spaceappschallenge.org/",
    "Open to all ages and backgrounds. Confirm your local or virtual event arrangements before registering.",
    "A team project, demo, and explanation of your own contribution.",
    {
      timing: "Nov 14–15, 2026 · event dates",
      eventDate: "2026-11-14",
      endDate: "2026-11-15",
      format: "Hybrid",
      cost: "Check event",
      review: true,
      source: "https://www.nasa.gov/prizes-challenges-and-crowdsourcing/",
    },
  ),
  item(
    "usaco",
    "USACO contests & training",
    "USA Computing Olympiad",
    "Olympiad practice",
    ["Computer Science", "Mathematics"],
    "Practice algorithms and participate in online programming contests.",
    "https://usaco.org/index.php?page=instructions",
    "Online contests and training welcome everyone. U.S. camp and team selection has separate pre-college eligibility; participation does not imply team eligibility.",
    "A practice log with original explanations of solved problems.",
    { timing: "Training anytime · contest dates vary", review: true },
  ),
  item(
    "euler",
    "Project Euler",
    "Project Euler",
    "Olympiad practice",
    ["Mathematics", "Computer Science", "Physics"],
    "Work through mathematical programming problems at your own pace.",
    "https://projecteuler.net/about",
    "Open to learners and adults. A free account tracks your solved problems. Follow the platform’s solution-sharing rules.",
    "A private problem-solving journal and record of progress.",
  ),
  item(
    "unv",
    "UN online volunteering",
    "United Nations Volunteers",
    "Volunteering",
    [
      "Communications",
      "Education",
      "Political Science",
      "Sociology",
      "English",
      "Journalism",
      "Business Administration",
      "Computer Science",
    ],
    "Apply to remote assignments supporting organizations working on development challenges.",
    "https://www.unv.org/become-online-volunteer",
    "Age 18+. Each host sets assignment requirements. Unpaid, up to 20 hours/week for up to 12 weeks; volunteering is not UN employment.",
    "Work agreed with your host and their feedback on your contribution.",
    {
      minAge: 18,
      review: true,
      timing: "Assignment deadlines vary",
      apply: "https://app.unv.org/",
    },
  ),
  item(
    "zooniverse",
    "Citizen science projects",
    "Zooniverse",
    "Research participation",
    [
      "Biology",
      "Psychology",
      "Physics",
      "Environmental Science",
      "History",
      "Sociology",
    ],
    "Help researchers classify real data in science and humanities projects.",
    "https://www.zooniverse.org/projects",
    "No specialist background is required. Read the selected project’s tutorial and participation rules.",
    "A contribution log and a reflection on the research question and method.",
    { source: "https://www.zooniverse.org/about" },
  ),
  item(
    "maps",
    "Humanitarian mapping",
    "Missing Maps",
    "Volunteering",
    [
      "Environmental Science",
      "Political Science",
      "Sociology",
      "Computer Science",
      "Engineering",
    ],
    "Contribute to open maps used in humanitarian work, individually or at a mapathon.",
    "https://www.missingmaps.org/",
    "Beginner resources are available. Complete the mapping tutorial and follow task-specific instructions.",
    "Documented mapping contributions and a short explanation of their context.",
  ),
  item(
    "proofread",
    "Preserve public-domain books",
    "Distributed Proofreaders",
    "Volunteering",
    ["English", "History", "Journalism", "Communications", "Music"],
    "Proofread digitized pages that become accessible Project Gutenberg texts.",
    "https://www.pgdp.net/c/",
    "Complete the beginner walkthrough. Flexible participation; the project does not certify volunteer hours or identity.",
    "A personal contribution log and reflections on editorial accuracy.",
  ),
  item(
    "inaturalist",
    "Biodiversity observations",
    "iNaturalist",
    "Research participation",
    ["Biology", "Environmental Science"],
    "Document biodiversity observations and learn through community identification.",
    "https://www.inaturalist.org/pages/about",
    "Follow platform terms and local access rules. Avoid sharing sensitive locations or disturbing wildlife.",
    "An observation collection and a carefully qualified local biodiversity report.",
    { format: "Local" },
  ),
  item(
    "forage",
    "Career job simulations",
    "Forage",
    "Career exploration",
    [
      "Business Administration",
      "Economics",
      "Computer Science",
      "Engineering",
      "Communications",
      "Political Science",
    ],
    "Try self-paced tasks based on professional work to explore a field before committing.",
    "https://www.theforage.com/",
    "Free, open-access simulations. These are learning experiences, not internships or employment.",
    "Completed exercises and a reflection on skills you want to develop.",
  ),
  item(
    "ocw",
    "MIT OpenCourseWare",
    "MIT",
    "Course",
    MAJORS,
    "Use university course materials to build foundations for an independent project.",
    "https://ocw.mit.edu/",
    "No enrollment required. Select a level that fits your background. OCW offers no credit, degree, or certificate.",
    "Completed exercises and an original project applying what you learned.",
    { source: "https://ocw.mit.edu/pages/get-started/" },
  ),
  item(
    "openlearn",
    "OpenLearn short courses",
    "The Open University",
    "Course",
    MAJORS,
    "Explore free courses across science, society, business, health, and the arts.",
    "https://www.open.edu/openlearn/free-courses",
    "Check course level and estimated hours. Statements of participation do not carry formal academic credit.",
    "A course activity record and a practical application of one concept.",
    {
      source:
        "https://www.open.edu/openlearn/about-openlearn/frequently-asked-questions-on-openlearn",
    },
  ),
  item(
    "devpost",
    "Find a public hackathon",
    "Devpost",
    "Opportunity directory",
    [
      "Computer Science",
      "Engineering",
      "Fine Arts",
      "Business Administration",
      "Music",
    ],
    "Browse current online and in-person hackathons by theme and location.",
    "https://devpost.com/hackathons",
    "Directory, not a single program. Age, country, fees, dates, and judging rules depend on the organizer.",
    "A specific event shortlist after checking the official rules.",
    {
      cost: "Varies",
      format: "Hybrid",
      review: true,
      timing: "Event deadlines vary",
      source: "https://info.devpost.com/faqs-participants",
    },
  ),
  item(
    "mlh",
    "Student hackathon calendar",
    "Major League Hacking",
    "Opportunity directory",
    ["Computer Science", "Engineering", "Fine Arts"],
    "Find student-focused events and check whether a recent graduate can participate.",
    "https://www.mlh.com/seasons/2027/events",
    "MLH guidelines generally count people who graduated within 12 months as students. Each event’s rules determine admission. Member events have free admission; travel may cost extra.",
    "A verified eligible event and, after attending, your project demo.",
    {
      format: "Hybrid",
      review: true,
      timing: "Event deadlines vary",
      source:
        "https://github.com/MLH/mlh-policies/blob/main/standard-hackathon-rules.md",
    },
  ),
  item(
    "gsoc",
    "Google Summer of Code",
    "Google",
    "Open source",
    ["Computer Science", "Engineering", "Mathematics"],
    "Prepare for a mentored contribution to an open-source organization.",
    "https://summerofcode.withgoogle.com/get-started",
    "Age 18+, student or open-source beginner, eligible to work where you live, and country restrictions apply. Review the current contributor terms.",
    "A contribution history and a project proposal when the next cycle opens.",
    {
      minAge: 18,
      review: true,
      status: "next-cycle",
      timing: "Prepare for a future cycle · check schedule",
    },
  ),
  item(
    "kaggle",
    "Data science competitions",
    "Kaggle",
    "Opportunity directory",
    [
      "Computer Science",
      "Mathematics",
      "Economics",
      "Biology",
      "Physics",
      "Chemistry",
    ],
    "Find a data challenge and build a reproducible baseline before chasing a leaderboard score.",
    "https://www.kaggle.com/competitions",
    "Competition-specific rules, country restrictions, and age-of-majority requirements apply. Some sponsors allow minors with consent. Check rules before entering.",
    "A reproducible notebook, error analysis, and honest account of your contribution.",
    {
      review: true,
      cost: "Check event",
      timing: "Competition deadlines vary",
      source: "https://www.kaggle.com/terms",
    },
  ),
];
