// Official-source research, reviewed 24 September 2026. Steps and outputs are
// MyGapMentor suggestions, not promises made by the host organizations.
export function extraOpportunities(item, all) {
  const cs = ["Computer Science", "Engineering", "Mathematics"];
  const science = [
    "Biology",
    "Chemistry",
    "Physics",
    "Environmental Science",
    "Mathematics",
  ];
  const humanities = [
    "History",
    "English",
    "Journalism",
    "Political Science",
    "Sociology",
  ];
  return [
    item(
      "nasa-ostem",
      "NASA OSTEM internships",
      "NASA",
      "Internship",
      all,
      "Work on a NASA project through a selective, paid internship in STEM or a supporting field.",
      "https://www.nasa.gov/learning-resources/internship-programs/",
      "U.S. citizen, age 16+ at application, GPA 3.0+. Current college certificate/degree enrollment is required; recent higher-education graduates have a limited three-session exception. A high-school gap year alone does not qualify.",
      "An application matched to a specific role; if selected, a supervised project and an approved account of your work.",
      {
        minAge: 16,
        stages: ["college"],
        review: true,
        status: "seasonal",
        cost: "Check program",
        format: "Hybrid",
        deadline: "2027-02-26",
        timing:
          "Summer 2027 applications due February 26, 2027, 11:59 p.m. ET; spring deadline has passed",
        commitment:
          "Summer: 10 weeks; spring/fall: 15 weeks. Check each position’s schedule and location.",
        keywords: "nasa internship space aerospace summer paid",
        steps: [
          "Check college enrollment, citizenship, GPA, and the selected session’s requirements.",
          "Choose two specific STEM Gateway roles and tailor your resume to their required skills.",
          "Prepare the requested application materials and submit only while that session is accepting applications.",
        ],
      },
    ),
    item(
      "smithsonian",
      "Smithsonian digital transcription",
      "Smithsonian Institution",
      "Volunteering",
      [...humanities, "Fine Arts", "Biology"],
      "Transcribe collection records so historical and scientific materials become searchable.",
      "https://transcription.si.edu/",
      "Anyone with internet access can contribute, including anonymously. Follow the project’s transcription and review instructions; this is unpaid volunteering.",
      "Links to transcribed pages, a contribution log, and a short explanation of the collection’s significance.",
      {
        source: "https://transcription.si.edu/faqs",
        commitment: "Self-paced; choose a page or a short session.",
        steps: [
          "Choose an unfinished collection and read How to Transcribe.",
          "Transcribe one page carefully, preserving the original wording.",
          "Record your page link and review corrections before taking another page.",
        ],
      },
    ),
    item(
      "citizen-archivist",
      "Citizen Archivist",
      "U.S. National Archives",
      "Volunteering",
      humanities,
      "Tag and transcribe primary sources to improve public access to government records.",
      "https://www.archives.gov/citizen-archivist",
      "A free Catalog account using Login.gov is needed to contribute. Review the contribution policy and transcription guidance.",
      "A dated record of contributions and a sourced mini-exhibit about a historical question.",
      {
        review: true,
        source:
          "https://www.archives.gov/citizen-archivist/register-and-get-started",
        commitment: "Self-paced; missions vary in complexity.",
        steps: [
          "Register for the Catalog and read the transcription tips.",
          "Choose a beginner mission and transcribe or tag one record.",
          "Save record identifiers and explain how your work improves discoverability.",
        ],
      },
    ),
    item(
      "picogym",
      "picoGym cybersecurity practice",
      "Carnegie Mellon University · picoCTF",
      "Practice",
      cs,
      "Solve cybersecurity challenges in a noncompetitive practice environment.",
      "https://picoctf.org/get_started.html",
      "Use the practice platform under its account terms. Competition prizes have separate age, school, and location rules; practicing is not a competition award.",
      "A skills journal describing approaches, mistakes, and independently solved challenges.",
      {
        review: true,
        commitment: "Self-paced practice; start with beginner challenges.",
        keywords: "cyber security hacking ctf",
        steps: [
          "Read the getting-started guide and choose a beginner challenge.",
          "Solve it in the provided environment and explain why the solution works.",
          "Attempt another category and document what you learned without exposing active contest answers.",
        ],
      },
    ),
    item(
      "foldit",
      "Foldit protein puzzles",
      "Foldit research community",
      "Research participation",
      ["Biology", "Chemistry", "Computer Science", "Mathematics"],
      "Explore protein structure and design through a research puzzle game.",
      "https://www.fold.it/science",
      "Free to play. Complete the introductory puzzles and follow current research-puzzle instructions; participation does not guarantee authorship.",
      "A puzzle journal connecting design decisions to protein structure and documented contributions.",
      {
        source: "https://dev.fold.it/about_foldit",
        commitment: "Self-paced; introductory puzzles before research puzzles.",
        steps: [
          "Install Foldit using the official site and complete introductory puzzles.",
          "Read the science behind one current research puzzle.",
          "Try several designs and keep a comparison of your strategies and results.",
        ],
      },
    ),
    item(
      "ebird",
      "eBird field observations",
      "Cornell Lab of Ornithology",
      "Research participation",
      ["Biology", "Environmental Science", "Mathematics"],
      "Contribute structured bird observations and investigate patterns in local biodiversity.",
      "https://ebird.org/",
      "Free account and careful observation protocols. Record only birds you can identify; local access and field conditions vary.",
      "A series of complete checklists and a small analysis of a local birding question.",
      {
        format: "Local",
        source:
          "https://support.ebird.org/en/support/solutions/articles/48000948757",
        commitment:
          "Self-paced field visits, with effort and location recorded.",
        steps: [
          "Complete the free eBird Essentials introduction.",
          "Submit a checklist with accurate effort and location information.",
          "Repeat observations at one site and graph a pattern, noting sampling limitations.",
        ],
      },
    ),
    item(
      "scistarter",
      "SciStarter project finder",
      "SciStarter",
      "Opportunity directory",
      science,
      "Find citizen-science projects by topic, location, and the equipment you have.",
      "https://scistarter.org/",
      "Project-specific age, country, equipment, and training requirements apply. A directory listing is not a research placement.",
      "A verified project shortlist and a contribution log from the project you actually join.",
      {
        review: true,
        cost: "Varies",
        source: "https://pages.scistarter.org/citizen-science/",
        timing: "Project availability varies",
        commitment: "Varies by project.",
        steps: [
          "Filter for your subject, location, and available equipment.",
          "Open the project’s own site and confirm it is collecting contributions.",
          "Complete its training, make a first contribution, and record the result.",
        ],
      },
    ),
    item(
      "exercism",
      "Exercism programming practice",
      "Exercism",
      "Practice",
      cs,
      "Practice a programming language through exercises and community feedback.",
      "https://exercism.org/",
      "Free learning and practice. Feedback availability depends on community volunteers; follow platform terms.",
      "Revised solutions with tests and notes explaining improvements after feedback.",
      {
        source: "https://exercism.org/mentoring",
        commitment: "Self-paced exercises.",
        steps: [
          "Choose one language track and complete its first exercise.",
          "Write tests and request feedback where available.",
          "Revise your solution and explain the tradeoffs in a learning journal.",
        ],
      },
    ),
    item(
      "odin",
      "The Odin Project",
      "The Odin Project",
      "Course",
      cs,
      "Build web projects through a free, open-source development curriculum.",
      "https://www.theodinproject.com/",
      "Beginner-friendly self-study with a suitable computer. This is a curriculum, not an internship or accredited qualification.",
      "A deployed project, source repository, and a short case study of your design choices.",
      {
        source: "https://www.theodinproject.com/faq",
        commitment: "Self-paced; substantial projects take sustained work.",
        steps: [
          "Start Foundations and set up the recommended development environment.",
          "Complete a project from the curriculum in your own code.",
          "Publish it, test it with someone, and document a revision.",
        ],
      },
    ),
    item(
      "red-cross",
      "Red Cross community volunteering",
      "American Red Cross",
      "Volunteering",
      [
        "Nursing",
        "Psychology",
        "Education",
        "Communications",
        "Sociology",
        "Business Administration",
      ],
      "Find a local service role and receive the training required for that assignment.",
      "https://www.redcross.org/volunteer/volunteer-opportunities.collection.html",
      "U.S. roles vary by location, minimum age, availability, and screening. Youth and adult roles differ; volunteering is not clinical training.",
      "A supervisor-confirmed service record and reflection on a specific community contribution.",
      {
        review: true,
        format: "Hybrid",
        source:
          "https://www.redcross.org/volunteer/become-a-volunteer/youth-opportunities.html",
        timing: "Local openings and onboarding vary",
        commitment: "Role-specific shifts and minimum commitments.",
        steps: [
          "Search your postal code and filter by minimum age.",
          "Choose a role whose commitment fits and complete volunteer intake.",
          "Complete required training and agree on a first shift with the coordinator.",
        ],
      },
    ),
    item(
      "habitat",
      "Habitat community volunteering",
      "Habitat for Humanity",
      "Volunteering",
      [
        "Engineering",
        "Business Administration",
        "Political Science",
        "Sociology",
        "Communications",
      ],
      "Support housing work through a local affiliate, ReStore, or community activity.",
      "https://www.habitat.org/volunteer/near-you/youth-programs",
      "Local affiliates set role-specific ages, supervision, availability, and participation conditions. Construction access is not available to every age group.",
      "A service log and an account of a concrete housing or community-support contribution.",
      {
        review: true,
        format: "Local",
        cost: "Check program",
        timing: "Local schedules vary",
        commitment: "Confirm shifts and any costs with the affiliate.",
        steps: [
          "Find your local Habitat affiliate and read its volunteer options.",
          "Ask which role fits your age, transport, and available hours.",
          "Complete orientation and document the work you perform with the team.",
        ],
      },
    ),
    item(
      "twb",
      "Humanitarian language volunteering",
      "Translators without Borders · CLEAR Global",
      "Volunteering",
      [
        "English",
        "Communications",
        "Journalism",
        "Political Science",
        "Nursing",
      ],
      "Help make humanitarian information accessible through translation and related language tasks.",
      "https://translatorswithoutborders.org/join-the-twb-community/",
      "Age 18+, fluency in a language besides your native language, internet access, and ability to meet deadlines. Formal translation experience is not required.",
      "A verified contribution record and reflection on language decisions, without publishing confidential source material.",
      {
        minAge: 18,
        review: true,
        commitment: "Task-specific deadlines; choose work you can finish.",
        steps: [
          "Create a community profile with your actual language skills.",
          "Review the style guides and select a suitable available task.",
          "Complete it by the agreed deadline and record feedback and contribution totals.",
        ],
      },
    ),
    item(
      "schoolhouse",
      "Schoolhouse peer tutoring",
      "Schoolhouse.world",
      "Volunteering",
      [
        "Education",
        "Mathematics",
        "Computer Science",
        "Physics",
        "Chemistry",
        "Psychology",
      ],
      "Demonstrate subject mastery and help other learners through online tutoring.",
      "https://schoolhouse.world/certification/about",
      "Age 13+ to learn or tutor. Tutors must demonstrate mastery through certification and complete applicable tutor training.",
      "A tutor certification transcript, prepared explanations, and a record of completed sessions.",
      {
        minAge: 13,
        review: true,
        commitment: "Certification and training first; session schedules vary.",
        steps: [
          "Choose a subject you understand well and read its certification requirements.",
          "Complete the mastery check and tutor training.",
          "Prepare an explanation, host an approved session, and reflect on learner feedback.",
        ],
      },
    ),
    item(
      "diamond",
      "Diamond Challenge",
      "University of Delaware · Horn Entrepreneurship",
      "Competition",
      [
        "Business Administration",
        "Economics",
        "Engineering",
        "Communications",
        "Sociology",
      ],
      "Develop and pitch an original business or social venture with a student team.",
      "https://diamondchallenge.org/competition/",
      "Teams of 2–4 high-school students aged 14–18 at submission, with an adult advisor aged 21+. Graduates are not eligible under the published school requirement.",
      "A customer-tested concept, 3–5 page narrative, and 60-second introductory video.",
      {
        minAge: 14,
        maxAge: 18,
        stages: ["school"],
        review: true,
        status: "seasonal",
        deadline: "2027-01-14",
        timing:
          "2027 submissions: September 16, 2026–January 14, 2027, 5 p.m. EST",
        commitment:
          "Team concept development over several months; later rounds require pitching.",
        steps: [
          "Confirm every teammate’s eligibility and recruit an adult advisor.",
          "Interview potential users and test your business or social-impact idea.",
          "Prepare the narrative and introduction video against the official submission checklist.",
        ],
      },
    ),
    item(
      "technovation",
      "Technovation Girls",
      "Technovation",
      "Competition",
      [
        "Computer Science",
        "Engineering",
        "Business Administration",
        "Communications",
      ],
      "Create an app or AI project addressing a community problem, with a business plan and pitch.",
      "https://technovationchallenge.org/get-involved/students/",
      "Published program ages 8–18, for girls and eligible nonbinary, gender-nonconforming, and transgender participants. Check the next season’s exact age date and terms. The learning curriculum is available more broadly.",
      "A working prototype, user research, business plan, and pitch video.",
      {
        minAge: 8,
        maxAge: 18,
        review: true,
        status: "next-cycle",
        timing:
          "Watch for 2026–27 registration; do not use last season’s deadlines",
        commitment:
          "A sustained team project across the program season; equipment is not supplied.",
        steps: [
          "Check new-season eligibility and registration on the student page.",
          "Find teammates and identify a real community problem through interviews.",
          "Use the curriculum to prototype a solution and prepare the required pitch.",
        ],
      },
    ),
    item(
      "outreachy",
      "Outreachy open-source internships",
      "Outreachy · Software Freedom Conservancy",
      "Open source",
      ["Computer Science", "Communications", "Fine Arts", "English"],
      "Prepare for a selective, paid internship contributing to an open-source community.",
      "https://www.outreachy.org/docs/applicant/",
      "Age 18+ by internship start; detailed underrepresentation, residency, prior-internship, and time-availability criteria apply. Nonstudents can apply; students have additional calendar rules.",
      "A record of accepted contributions and a focused application; a mentored project if selected.",
      {
        minAge: 18,
        minHours: 30,
        review: true,
        status: "next-cycle",
        cost: "Check program",
        timing:
          "December 2026 initial applications closed August 31; prepare for a future round",
        commitment:
          "30 hours/week during the internship; December round runs December 7, 2026–March 8, 2027.",
        steps: [
          "Read all eligibility and time-availability rules before preparing an application.",
          "Explore participating communities and learn their contribution workflow.",
          "Build relevant skills now; follow the next initial-application and contribution windows.",
        ],
      },
    ),
    item(
      "lfx",
      "LFX Mentorship",
      "Linux Foundation",
      "Open source",
      cs,
      "Apply to a project-specific mentorship and contribute to maintained open-source software.",
      "https://docs.linuxfoundation.org/lfx/mentorship",
      "Age 18+ at start, work eligibility and location restrictions, no prior/active Linux Foundation mentorship, and each project’s prerequisites apply.",
      "A tested contribution, technical write-up, and project-specific application materials.",
      {
        minAge: 18,
        review: true,
        status: "seasonal",
        cost: "Check program",
        source:
          "https://docs.linuxfoundation.org/lfx/mentorship/mentee-guide/am-i-eligible",
        timing: "Project and cohort application windows vary",
        commitment:
          "Read each mentorship’s duration, weekly hours, and stipend terms.",
        steps: [
          "Choose a listed mentorship and confirm its prerequisites and schedule.",
          "Build the project locally and complete the required application tasks.",
          "Submit a focused application with evidence of your own contributions.",
        ],
      },
    ),
    item(
      "foyle",
      "Foyle Young Poets Award",
      "The Poetry Society",
      "Competition",
      ["English", "Communications", "Fine Arts"],
      "Develop original poetry for an international award for young writers.",
      "https://poetrysociety.org.uk/competitions/foyle-young-poets-of-the-year-award/",
      "Poets aged 11–17 internationally. Confirm the next round’s age reference date, submission rules, and fees before entering.",
      "A carefully revised selection of poems and an editing journal.",
      {
        minAge: 11,
        maxAge: 17,
        review: true,
        status: "next-cycle",
        cost: "Check event",
        timing: "2026 entries closed; next round not yet verified",
        commitment:
          "Self-paced drafting and revision before the next entry window.",
        steps: [
          "Read previous winning poems and the next round’s published rules.",
          "Draft a small group of poems and seek specific critique.",
          "Revise your strongest work and check publication restrictions before sharing or submitting.",
        ],
      },
    ),
    item(
      "youngarts",
      "YoungArts national arts competition",
      "YoungArts",
      "Competition",
      ["Fine Arts", "Music", "English", "Communications"],
      "Submit an original visual, literary, or performing-arts portfolio for national adjudication.",
      "https://youngarts.org/apply/",
      "Grades 10–12 OR ages 15–18 on December 1, 2026. U.S. citizenship, permanent residence, or eligibility to receive taxable U.S. income is required; check all discipline and prior-award rules.",
      "A discipline-specific portfolio or audition recording and a documented revision process.",
      {
        review: true,
        status: "seasonal",
        cost: "Check program",
        deadline: "2026-10-06",
        timing: "2027 competition deadline: October 6, 2026, 8 p.m. ET",
        commitment:
          "Portfolio preparation varies by discipline. Check application fee and waiver options.",
        steps: [
          "Use the official eligibility questionnaire and select your discipline.",
          "Review its exact portfolio or audition requirements and fee-waiver options.",
          "Prepare original work, check file specifications, and submit before the deadline.",
        ],
      },
    ),
    item(
      "john-locke",
      "John Locke Global Essay Prize",
      "John Locke Institute",
      "Competition",
      ["Economics", "Psychology", "History", "English", "Political Science"],
      "Develop a reasoned, evidence-based response to a challenging academic question.",
      "https://www.johnlockeinstitute.com/essay-competition",
      "Under 19 on the regular 2026 submission deadline, May 31. Academic referee required. Standard entry is free; late options and optional events can cost extra. Recheck next-year rules.",
      "An original argument, annotated research notes, and a revised essay.",
      {
        maxAge: 18,
        review: true,
        status: "next-cycle",
        timing:
          "2026 regular deadline passed; prepare for the next announced round",
        commitment:
          "Independent reading, argument development, and revision; 2026 limit was 2,000 words.",
        steps: [
          "Read the published questions and select one you can investigate deeply.",
          "Compare credible sources, test counterarguments, and draft your own position.",
          "Revise with feedback and check new-round referee, format, and deadline requirements.",
        ],
      },
    ),
    item(
      "breakthrough",
      "Breakthrough Junior Challenge",
      "Breakthrough Prize Foundation",
      "Competition",
      ["Physics", "Biology", "Mathematics", "Communications"],
      "Explain a difficult scientific idea through an original educational video.",
      "https://breakthroughjuniorchallenge.org/",
      "2026 rules: at least 13 by May 11 and not yet 19 on October 1. Guardian permission for minors, country restrictions, and prior-winner exclusions apply. Check the next round’s rules.",
      "A clear science explainer with a script, credible references, and audience feedback.",
      {
        minAge: 13,
        maxAge: 18,
        source: "https://breakthroughjuniorchallenge.org/rules",
        review: true,
        status: "next-cycle",
        cost: "Free",
        timing:
          "2026 entry deadline was September 15; peer review continues for existing entrants",
        commitment:
          "Research and production; 2026 required a video up to 2 minutes and review of at least five peers.",
        steps: [
          "Study the current judging criteria and eligibility rules.",
          "Choose one scientific concept and storyboard an accurate explanation.",
          "Test your explanation with a learner and prepare for the next verified submission round.",
        ],
      },
    ),
    item(
      "gwc-pathways",
      "Girls Who Code Pathways",
      "Girls Who Code",
      "Summer program",
      ["Computer Science", "Engineering", "Mathematics"],
      "Explore coding tracks through a free virtual summer program with projects and community events.",
      "https://girlswhocode.com/GWC-Pathways-Summer-INTL-Flyer",
      "The 2026 program welcomed girls and nonbinary students aged 14–18, including beginners and alumni. Confirm enrollment and age rules for the next round.",
      "A finished coding project and a reflection on the track you explored.",
      {
        minAge: 14,
        maxAge: 18,
        review: true,
        status: "next-cycle",
        timing:
          "2026 program ended August 14; application deadline was April 10",
        commitment:
          "2026 courses took 3–6 hours each, with optional community events.",
        keywords: "summer camp coding ai data science",
        steps: [
          "Check whether a new Pathways cohort has been announced.",
          "Choose a track and practice its foundations with a free learning resource.",
          "When eligible registration opens, apply and plan a small project to complete.",
        ],
      },
    ),
    item(
      "globe-observer",
      "GLOBE Observer",
      "The GLOBE Program · NASA-supported science",
      "Research participation",
      ["Environmental Science", "Physics", "Biology", "Mathematics"],
      "Collect environmental observations that help researchers interpret satellite data.",
      "https://observer.globe.gov/do-globe-observer",
      "Anyone in a participating GLOBE country with a compatible device can use the app. Confirm country availability and follow each observation protocol.",
      "A repeatable observation series with charts and a clear account of measurement limits.",
      {
        review: true,
        format: "Local",
        source: "https://observer.globe.gov/en/about/get-the-app",
        commitment: "Self-paced outdoor observations using the app.",
        steps: [
          "Check your country and device, then create a citizen-science account.",
          "Complete one tool’s tutorial and submit an observation.",
          "Repeat the protocol and compare your observations over time.",
        ],
      },
    ),
    item(
      "stall-catchers",
      "Stall Catchers",
      "Human Computation Institute · EyesOnALZ",
      "Research participation",
      ["Biology", "Psychology", "Nursing", "Computer Science"],
      "Classify blood-vessel images in an online project supporting Alzheimer’s research.",
      "https://stallcatchers.com/main",
      "Open to volunteers without specialist expertise. Register and follow the classification training; this is image analysis, not clinical work.",
      "A contribution record and an explanation of classification uncertainty and the research question.",
      {
        review: true,
        commitment: "Self-paced online classifications.",
        steps: [
          "Register and complete the introductory classification training.",
          "Classify a small batch carefully and review the feedback.",
          "Keep a contribution log and explain why crowd agreement matters.",
        ],
      },
    ),
    item(
      "solidarity",
      "European Solidarity Corps volunteering",
      "European Commission",
      "Volunteering",
      all,
      "Join a supported community-service placement individually or with an international team.",
      "https://youth.europa.eu/solidarity/young-people/volunteering_en",
      "Ages 18–30 and residence in an EU or other covered country. Each host has selection requirements. Registration does not guarantee a placement.",
      "A completed community project, service record, and reflection on your role and learning.",
      {
        minAge: 18,
        maxAge: 30,
        minHours: 30,
        review: true,
        format: "Local",
        cost: "Check program",
        timing: "Host application windows vary",
        commitment:
          "Full time, 30–38 hours/week. Individual projects: 2 weeks–12 months; teams: 2 weeks–2 months. Basic costs are supported under program terms.",
        steps: [
          "Confirm residence eligibility and the supported costs for the placement.",
          "Create an EU Login and Corps profile, then choose a suitable host project.",
          "Discuss responsibilities and logistics with the host before committing.",
        ],
      },
    ),
    item(
      "advent",
      "Advent of Code practice",
      "Eric Wastl",
      "Practice",
      cs,
      "Solve archived programming puzzles at your own pace using a language you want to improve.",
      "https://adventofcode.com/about",
      "Free to use; some programming knowledge helps. Respect the organizer’s rules on sharing puzzle content and solving independently.",
      "Your own tested solutions and notes comparing approaches, without redistributing puzzle inputs or text.",
      {
        commitment:
          "Self-paced archived puzzles; live events have a separate schedule.",
        steps: [
          "Choose an early puzzle from an archived event.",
          "Write your own solution and test it on small cases.",
          "Refactor it and record complexity and edge cases without reposting the puzzle.",
        ],
      },
    ),
    item(
      "beamline",
      "Beamline for Schools",
      "CERN · DESY · University of Bonn",
      "Competition",
      ["Physics", "Engineering", "Mathematics"],
      "Develop a team proposal for an experiment using a particle beam.",
      "https://beamlineforschools.cern/",
      "School-team and age conditions apply. Published pages differ on gap-year participation; confirm next-round eligibility with the organizers before investing in an application.",
      "An experiment proposal explaining the hypothesis, apparatus, measurements, and uncertainty.",
      {
        review: true,
        status: "next-cycle",
        cost: "Check event",
        source: "https://beamlineforschools.cern/about",
        timing:
          "2026 proposal deadline was March 13; future round not yet verified",
        commitment: "A substantial team research proposal with a coach.",
        steps: [
          "Confirm next-round eligibility, especially if you have already graduated.",
          "Study the available beam and detector resources with a coach.",
          "Design a feasible experiment and explain its measurement and uncertainty plan.",
        ],
      },
    ),
    item(
      "nasa-citizen",
      "NASA citizen-science projects",
      "NASA Science",
      "Opportunity directory",
      science,
      "Find public research projects in space science, Earth science, and related fields.",
      "https://science.nasa.gov/get-involved/citizen-science/you-can-help-humans-thrive-in-space/",
      "The featured projects welcome volunteers worldwide without a U.S.-citizenship requirement. Check each project’s current activity, tools, and participation instructions.",
      "A project contribution record and a sourced explanation of the scientific question.",
      {
        review: true,
        cost: "Check project",
        timing: "Check individual projects for active tasks",
        commitment: "Project-specific; many offer self-paced online tasks.",
        steps: [
          "Choose an active project from NASA’s official list.",
          "Follow its tutorial and complete a small first task.",
          "Record your contribution and explain how the data supports the research.",
        ],
      },
    ),
  ];
}
